<?php
/**
 * @file
 * Create custom ting facets.
 */

/**
 * Implements hook_menu().
 */
function ting_facet_custom_menu() {
  $menu = array();

  $menu['admin/config/ting/facets_custom'] = array(
    'title' => 'Ting facets custom',
    'description' => 'Define custom ting facets.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_facet_custom_admin_form'),
    'access arguments' => array('configure ting custom facets'),
    'file' => 'ting_facet_custom.admin.inc',
  );

  return $menu;
}

/**
 * Implements hook_permission().
 */
function ting_facet_custom_permission() {
  $perm = array();

  $perm['configure ting custom facets'] = array(
    'title' => t('Configure ting custom facets'),
    'description' => t('Grant roles to administer custom ting facets'),
  );

  return $perm;
}

/**
 * Implements hook_theme().
 */
function ting_facet_custom_theme($existing, $type, $theme, $path) {
  $hooks = array();

  $hooks['ting_facet_custom_facet_element'] = array(
    'render element' => 'element',
  );

  $hooks['ting_facet_custom_checkboxes'] = array(
    'render element' => 'element',
  );

  $hooks['ting_facet_custom'] = array(
    'variables' => array(),
  );

  return $hooks;
}

/**
 * Custom theming callback for block content.
 *
 * @see ting_facet_custom_block_view()
 * @see ting_facet_custom_theme()
 */
function theme_ting_facet_custom($variables) {
  $facets = variable_get('facets_wrapper', array());
  $form = drupal_get_form('ting_facet_custom_facet_form', $facets);

  return drupal_render($form);
}

/**
 * Custom theming callback for FE facet checkboxes.
 *
 * Handle checkboxes display, as well as specific markup for those.
 *
 * @see ting_facet_custom_facet_form()
 * @see ting_facet_custom_theme()
 */
function theme_ting_facet_custom_checkboxes($variables) {
  global $base_root;

  $element = $variables['element'];
  $facet_identifier = $element['#additional_attributes']['facet_identifier'];
  $facet_terms = $element['#additional_attributes']['facet_terms'];
  $request = urldecode(request_uri());
  $uri_parts = explode('?', $request);

  foreach ($facet_terms as $terms) {
    $facet_is_set = FALSE;
    $facet = ' and facet.department=("' . implode('" or "', $terms['terms']) . '")';

    // When the custom facet is already clicked (or exists in URL).
    if (mb_strpos($request, $facet) !== FALSE) {
      $facet_is_set = TRUE;
      $matches = array();
      preg_match('/(.*) and facet\.department=(.*)/', $request, $matches);

      $query = $matches[1];
      $uri = $query;
    }
    // When there is a plain text query string.
    else {
      $query = arg(2);
      $uri = $query . $facet;
    }

    // Append query parameters (facets) if any.
    if (!empty($uri_parts[1])) {
      $uri .= '?' . $uri_parts[1];
    }

    if (!$facet_is_set) {
      $uri = '/search/ting/' . $uri;
    }

    $link = l($terms['facet'], $base_root . $uri);

    $elements[] = array(
      '#type' => $element['#type'],
      '#title' => $link,
      '#name' => $facet_identifier,
      '#checked' => $facet_is_set,
    );
  }

  // Hide all checkboxes except the selected one.
  // Removes the ambiguity within selected facets.
  // Also emulated original facetbrowser behavior.
  $render = array_filter($elements, function($v) {
    return $v['#checked'];
  });

  if (!empty($render)) {
    $elements = $render;
  }

  $output = drupal_render($elements);

  return $output;
}

/**
 * FE facets checkboxes form.
 *
 * @param array $facets
 *   Saved custom facets from BE.
 */
function ting_facet_custom_facet_form($form, &$form_state, $facets) {
  if (empty($facets)) {
    return array();
  }

  $form['facet_wrapper'] = array(
    '#type' => 'fieldset',
    '#title' => check_plain($facets['title']),
  );

  $form['facet_wrapper']['facets'] = array(
    '#type' => 'checkbox',
    '#additional_attributes' => array(
      'facet_identifier' => $facets['identifier'],
      'facet_terms' => $facets['facets'],
    ),
    '#theme' => 'ting_facet_custom_checkboxes',
  );

  $form['#attached'] = array(
    'js' => array(
      drupal_get_path('module', 'ting_facet_custom') . '/js/ting_facet_custom.scripts.js',
    ),
    'css' => array(
      drupal_get_path('module', 'ting_facet_custom') . '/css/ting_facet_custom.styles.css',
    )
  );

  $form['#attributes'] = array(
    'class' => array(
      'ting-facet-custom-form',
    ),
  );

  return $form;
}

/**
 * Implements hook_block_info().
 */
function ting_facet_custom_block_info() {
  $blocks = array();

  $blocks['ting_facet_custom'] = array(
    'info' => t('Ting custom facet'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ting_facet_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'ting_facet_custom':
      $results = drupal_static('ting_search_results');
      $block['content'] = is_object($results) && $results->numTotalObjects > 0 ? theme('ting_facet_custom') : '';
      break;
  }

  return $block;
}

/**
 * Request terms for certain facet.
 *
 * @param string $facet
 *   Facet identifier.
 *
 * @return array
 *   Sorted list of facet terms.
 */
function ting_facet_custom_facets($facet = 'facet.department') {
  module_load_include('client.inc', 'ting');

  $options = array(
    'facets' => array($facet),
    'numFacets' => 9999,
    'reply_only' => TRUE,
    'sort' => 'random',
  );
  $result = ting_do_search("*", 0, 0, $options);

  $types = array();
  foreach ($result->facets[$facet]->terms as $term => $count) {
    $types[drupal_strtolower($term)] = $count;
  }

  $types = array_keys($types);
  sort($types);

  // Only save if we actually got any types.
  if (!empty($types)) {
    variable_set('ting_facet_custom_terms', $types);
  }

  return $types;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ting_facet_custom_preprocess_25_50_25(&$variables) {
  $search_result = arg(0) == 'search' && arg(1) == 'ting';

  if (!$search_result) {
    return;
  }

  $block = module_invoke('ting_facet_custom', 'block_view', 'ting_facet_custom');
  $custom_facet_markup =
    '<div class="panel-pane pane-block pane-ting-facet-custom">' .
    '<div class="pane-content">' .
    render($block['content']) .
    '</div>' .
    '</div>';


  $left_sidebar = $variables['content']['left_sidebar'];
  $target = '<div class="panel-pane pane-ding-facetbrowser"';
  $pos = strpos($left_sidebar, $target);
  $new_left_content = substr_replace($left_sidebar, $custom_facet_markup, $pos, 0);

  $variables['content']['left_sidebar'] = $new_left_content;
}
